# -*- coding: utf-8 -*-
"""RegLog_Con_Framework.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jf0U1JYFxO4L02eNj1cRltfbidwVqe09

# Dataset management
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

seeds = pd.read_csv('Pumpkin_Seeds.csv')
seeds.head()

seeds = seeds.sample(frac=1).reset_index(drop=True)
seeds.head()

seeds['Class'].replace(['Çerçevelik', 'Ürgüp Sivrisi'],[0, 1,], inplace= True)
seeds.head()

X = seeds.drop(['Class'], axis=1)
y = seeds['Class']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

print(X_train.shape,y_train.shape, X_test.shape, y_test.shape)

def minmax_norm(df):
  return (df - df.min()) / ( df.max() - df.min())

X_test = minmax_norm(X_test)
X_train = minmax_norm(X_train)

X_train.head()

model = LogisticRegression(dual = True, fit_intercept=True, solver='liblinear').fit(X_train, y_train)
model.score(X_test, y_test)

model.get_params()

y_pred = model.predict(X_test)
test_id = X_test.index

plt.figure(figsize=(50, 6))
plt.scatter(test_id,y_test, c = 'red')
plt.scatter(test_id,y_pred)
plt.show()